#!/bin/bash

pip install -r requirements.txt

rm ./divided_kingdom.sqlite3

./manage.py syncdb --noinput
./manage.py migrate --noinput

#./manage.py loadseed

./manage.py loaddata divided_kingdom/fixtures/seed/location.json
./manage.py loaddata divided_kingdom/fixtures/seed/route.json
./manage.py loaddata divided_kingdom/fixtures/seed/service.json
./manage.py loaddata divided_kingdom/fixtures/seed/itemtype.json
./manage.py loaddata divided_kingdom/fixtures/seed/motivatingforce.json
./manage.py loaddata divided_kingdom/fixtures/seed/user.json