
#Player Starting
BASE_HEALTH = 20
BASE_STAMINA = 20

STARTING_GOLD = 100
STARTING_ACTION_POINTS = 50
STARTING_SKILL_POINTS = 1

BASE_ATTACK = 10
BASE_DEFENSE = 20
BASE_SPEED = 1


#Other Settings (Not used yet, imported from .net version)
STRIKE_ROLL = 40
CRITICAL = 39
CRITICAL_MULTIPLER = 2
FUMBLE = 1
STAMINA_ATT_COST = 1
STRENGTH_DAMAGE_BONUS = 0.2 #//Every 5 points of strength give 1 additional point of damage

DAILY_ACTION_POINTS = 50

LEVEL_MIN_HP_GAIN = 5
LEVEL_MAX_HP_GAIN = 10

LEVEL_MIN_ST_GAIN = 6
LEVEL_MAX_ST_GAIN = 12

ATTRIBUTE_BASE = 5
ATTRIBUTE_MAX_VALUE = 20
ATTRIBUTE_BONUS_POINTS = 5

ARMOR_BASE = 5

STARTING_INVENTORY_SIZE = 20

MIN_UNARMED_DAMAGE = 1
MAX_UNARMED_DAMAGE = 3


BASE_ESCAPE_CHANCE = 50
BASE_MOB_ESCAPE_CHANCE = 25

COMBAT_RATE = 70
RUN_STAMINA_COST = 2

STARTING_LOCATION_ID = 1