import random

MOOD = (
    "Accomplished",
    "Aggravated",
    "Alone",
    "Amused",
    "Angry",
    "Annoyed",
    "Anxious",
    "Apathetic",
    "Ashamed",
    "Awake",
    "Bewildered",
    "Bitchy",
    "Blah",
    "Blissful",
    "Bored",
    "Bouncy",
    "Calm",
    "Cheerful",
    "Chipper",
    "Cold",
    "Complacent",
    "Confused",
    "Content",
    "Cranky",
    "Crappy",
    "Crazy",
    "Crushed",
    "Curious",
    "Cynical",
    "Dark",
    "Depressed",
    "Determined",
    "Devious",
    "Dirty",
    "Disappointed",
    "Discontent",
    "Ditzy",
    "Dorky",
    "Drained",
    "Drunk",
    "Ecstatic",
    "Energetic",
    "Enraged",
    "Enthralled",
    "Envious",
    "Exanimate",
    "Excited",
    "Exhausted",
    "Flirty",
    "Frustrated",
    "Full",
    "Geeky",
    "Giddy",
    "Giggly",
    "Gloomy",
    "Good",
    "Grateful",
    "Groggy",
    "Grumpy",
    "Guilty",
    "Happy",
    "High",
    "Hopeful",
    "Hot",
    "Hungry",
    "Hyper",
    "Impressed",
    "Indescribable",
    "Indifferent",
    "Infuriated",
    "Irate",
    "Irritated",
    "Jealous",
    "Jubilant",
    "Lazy",
    "Lethargic",
    "Listless",
    "Lonely",
    "Loved",
    "Mad",
    "Melancholy",
    "Mellow",
    "Mischievous",
    "Moody",
    "Morose",
    "Naughty",
    "Nerdy",
    "Numb",
    "Optimistic",
    "Peaceful",
    "Pessimistic",
    "Pissed off",
    "Pleased",
    "Predatory",
    "Quixotic",
    "Recumbent",
    "Refreshed",
    "Rejected",
    "Rejuvenated",
    "Relaxed",
    "Relieved",
    "Restless",
    "Rushed",
    "Sad",
    "Satisfied",
    "Shocked",
    "Sick",
    "Silly",
    "Sleepy",
    "Smart",
    "Stressed",
    "Surprised",
    "Sympathetic",
    "Thankful",
    "Tired",
    "Touched",
    "Uncomfortable",
    "Weird"
)

GOOD_MOOD = (
    "Amused",
    "Blissful",
    "Cheerful",
    "Chipper",
    "Content",
    "Energetic",
    "Excited",
    "Giddy",
    "Grateful",
    "Happy",
    "Hopeful",
    "Jubilant",
    "Peaceful",
    "Surprised",
    "Thankful",
)

BAD_MOOD = (
    "Aggravated",
    "Angry",
    "Annoyed",
    "Anxious",
    "Cranky",
    "Cynical",
    "Depressed",
    "Exhausted",
    "Frustrated",
    "Gloomy",
    "Grumpy",
    "Indifferent",
    "Infuriated",
    "Irate",
    "Stressed",
    "Uncomfortable",
)

NETURAL_MOOD = (
    "Bored",
    "Calm",
    "Complacent",
    "Content",
    "Indifferent",
    "Lazy",
    "Mellow",
    "Restless",
    "Sleepy",
    "Tired",
)

def get_random_mood():
    return random.choice(MOOD)


def update_merchant_mood(player_npc):
    if random.randint(1, 5) == 5:
        if player_npc.opinion_of_player < 5 and player_npc.opinion_of_player > -5:
            player_npc.mood = random.choice(NETURAL_MOOD)
        elif player_npc.opinion_of_player > 5:
            player_npc.mood = random.choice(GOOD_MOOD)
        elif player_npc.opinion_of_player < -5:
            player_npc.mood = random.choice(BAD_MOOD)
        elif player_npc.opinion_of_player < -50:
            player_npc.mood = "Infuriated"

        player_npc.save()
